import type { Product, Order, TrendReport, BestSellerItem, SubscriptionItem } from "@/types";

export const dummyProducts: Product[] = [
  {
    id: "1",
    name: "일회용 종이컵 6.5oz 1000개입",
    category: "소모품",
    price: 27500,
    unit_price: 27.5,
    unit: "박스",
    unit_amount: 1000,
    image_url: "",
    description: "카페/사무실용 표준 사이즈 종이컵",
    origin: "대한민국",
    shelf_life: "해당 없음",
    storage: "직사광선 피해 상온 보관",
    created_at: "2025-03-20",
  },
  {
    id: "2",
    name: "업소용 위생장갑 (L) 100매",
    category: "소모품",
    price: 4200,
    unit_price: 42,
    unit: "박스",
    unit_amount: 100,
    image_url: "",
    description: "식품 취급용 일회용 위생장갑",
    origin: "대한민국",
    shelf_life: "해당 없음",
    storage: "직사광선 피해 상온 보관",
    created_at: "2025-03-18",
  },
  {
    id: "3",
    name: "주방세제 3L 6개입",
    category: "소모품",
    price: 18500,
    unit_price: 3083,
    unit: "박스",
    unit_amount: 6,
    image_url: "",
    description: "업소용 대용량 주방세제",
    origin: "대한민국",
    shelf_life: "제조일로부터 3년",
    storage: "직사광선 피해 상온 보관",
    created_at: "2025-03-15",
  },
  {
    id: "4",
    name: "비닐봉투 (중) 1000매",
    category: "포장재",
    price: 11500,
    unit_price: 11.5,
    unit: "박스",
    unit_amount: 1000,
    image_url: "",
    description: "업소용 다용도 비닐봉투",
    origin: "대한민국",
    shelf_life: "해당 없음",
    storage: "직사광선 피해 상온 보관",
    created_at: "2025-03-14",
  },
  {
    id: "5",
    name: "업소용 식용유 18L",
    category: "식자재",
    price: 49000,
    unit_price: 2722,
    unit: "박스",
    unit_amount: 1,
    image_url: "",
    description: "대용량 식용유 프리미엄",
    origin: "대한민국",
    shelf_life: "제조일로부터 2년",
    storage: "직사광선 피해 서늘한 곳 보관",
    created_at: "2025-03-12",
  },
  {
    id: "6",
    name: "종이 양수푸 콜 (57mm) 100개입",
    category: "소모품",
    price: 16500,
    unit_price: 165,
    unit: "박스",
    unit_amount: 100,
    image_url: "",
    description: "POS 영수증 프린터용 감열지",
    origin: "대한민국",
    shelf_life: "해당 없음",
    storage: "직사광선 피해 상온 보관",
    created_at: "2025-03-10",
  },
  {
    id: "7",
    name: "주방 고무장갑 M 12켤레",
    category: "소모품",
    price: 12500,
    unit_price: 1041,
    unit: "박스",
    unit_amount: 12,
    image_url: "",
    description: "업소용 내구성 좋은 고무장갑",
    origin: "대한민국",
    shelf_life: "해당 없음",
    storage: "직사광선 피해 상온 보관",
    created_at: "2025-03-08",
  },
  {
    id: "8",
    name: "냅킨 2겹 200매 30팩",
    category: "소모품",
    price: 26000,
    unit_price: 866,
    unit: "박스",
    unit_amount: 30,
    image_url: "",
    description: "업소용 2겹 냅킨 대용량",
    origin: "대한민국",
    shelf_life: "해당 없음",
    storage: "직사광선 피해 상온 보관",
    created_at: "2025-03-05",
  },
  {
    id: "9",
    name: "아메리카노 원두 1kg (브라질산)",
    category: "식자재",
    price: 12700,
    unit_price: 12700,
    unit: "봉",
    unit_amount: 1,
    image_url: "",
    description: "브라질산 프리미엄 원두 1kg",
    origin: "브라질",
    shelf_life: "제조일로부터 1년",
    storage: "밀봉 후 서늘한 곳 보관",
    created_at: "2025-03-03",
  },
  {
    id: "10",
    name: "커피 필터 (백산화) 500매입",
    category: "소모품",
    price: 8900,
    unit_price: 17.8,
    unit: "박스",
    unit_amount: 500,
    image_url: "",
    description: "드립 커피용 백산화 필터",
    origin: "일본",
    shelf_life: "해당 없음",
    storage: "직사광선 피해 상온 보관",
    created_at: "2025-03-01",
  },
  {
    id: "11",
    name: "테이크아웃 커피컵 뚜껑 (1000개)",
    category: "포장재",
    price: 15000,
    unit_price: 15,
    unit: "박스",
    unit_amount: 1000,
    image_url: "",
    description: "종이컵 전용 뚜껑",
    origin: "대한민국",
    shelf_life: "해당 없음",
    storage: "직사광선 피해 상온 보관",
    created_at: "2025-02-28",
  },
  {
    id: "12",
    name: "설탕 스틱 1000개입",
    category: "식자재",
    price: 9800,
    unit_price: 9.8,
    unit: "박스",
    unit_amount: 1000,
    image_url: "",
    description: "카페용 개별 포장 설탕",
    origin: "대한민국",
    shelf_life: "제조일로부터 2년",
    storage: "직사광선 피해 상온 보관",
    created_at: "2025-02-25",
  },
  {
    id: "13",
    name: "커피 시럽 (바닐라) 1L",
    category: "식자재",
    price: 14700,
    unit_price: 14700,
    unit: "병",
    unit_amount: 1,
    image_url: "",
    description: "프리미엄 바닐라 시럽",
    origin: "프랑스",
    shelf_life: "개봉 후 3개월",
    storage: "개봉 후 냉장보관",
    created_at: "2025-02-20",
  },
  {
    id: "14",
    name: "멜로우 스푼 1050개입",
    category: "소모품",
    price: 5600,
    unit_price: 5.3,
    unit: "박스",
    unit_amount: 1050,
    image_url: "",
    description: "일회용 커피 스푼",
    origin: "대한민국",
    shelf_life: "해당 없음",
    storage: "직사광선 피해 상온 보관",
    created_at: "2025-02-18",
  },
  {
    id: "15",
    name: "종다 인스턴트 옥수수 100개입",
    category: "식자재",
    price: 8500,
    unit_price: 85,
    unit: "박스",
    unit_amount: 100,
    image_url: "",
    description: "인스턴트 옥수수차 티백",
    origin: "대한민국",
    shelf_life: "제조일로부터 2년",
    storage: "직사광선 피해 상온 보관",
    created_at: "2025-02-15",
  },
];

export const dummyOrders: Order[] = [
  {
    id: "1",
    order_number: "BM-20250325-0063",
    status: "배송완료",
    items: [
      { product_id: "1", product_name: "일회용 종이컵 6.5oz 외 2건", quantity: 2, unit_price: 27500, total_price: 55000 },
      { product_id: "2", product_name: "업소용 위생장갑 (L) 100매", quantity: 3, unit_price: 4200, total_price: 12600 },
      { product_id: "9", product_name: "아메리카노 원두 1kg (브라질산)", quantity: 5, unit_price: 12500, total_price: 62500 },
    ],
    total_amount: 130100,
    delivery_address: "서울시 마포구 합정동 123-45",
    delivery_date: "2025-03-27",
    is_cold: false,
    created_at: "2025-03-25",
    courier: "CJ대한통운",
    tracking_number: "123456789012",
    estimated_delivery: "2025년 3월 25일 (일)",
  },
  {
    id: "2",
    order_number: "BM-20250320-0051",
    status: "배송중",
    items: [
      { product_id: "5", product_name: "업소용 식용유 18L × 2박스", quantity: 2, unit_price: 49000, total_price: 98000 },
    ],
    total_amount: 98000,
    delivery_address: "서울시 마포구 합정동 123-45",
    delivery_date: "2025-03-22",
    is_cold: false,
    created_at: "2025-03-20",
    courier: "CJ대한통운",
    tracking_number: "123456789012",
    estimated_delivery: "2025년 3월 25일 (일)",
  },
  {
    id: "3",
    order_number: "BM-20250325-0063a",
    status: "주문완료",
    items: [
      { product_id: "8", product_name: "냅킨 2겹 200매 30팩 외 1건", quantity: 1, unit_price: 26000, total_price: 26000 },
      { product_id: "4", product_name: "비닐봉투 (중) 1000매", quantity: 1, unit_price: 26500, total_price: 26500 },
    ],
    total_amount: 52500,
    delivery_address: "서울시 마포구 합정동 123-45",
    delivery_date: "2025-04-03",
    is_cold: false,
    created_at: "2025-03-25",
  },
];

export const dummyTrendReport: TrendReport = {
  period: "weekly",
  top_product: "일회용 종이컵",
  top_category: "업소용 위생장갑",
  total_categories: 18,
  total_buyers: 342,
  items: [
    { rank: 1, product_name: "일회용 종이컵 6.5oz 1000개입", sales_count: "9,200", change: 32 },
    { rank: 2, product_name: "업소용 위생장갑 (L) 100매", sales_count: "8,520", change: 12 },
    { rank: 3, product_name: "아메리카노 원두 1kg", sales_count: "6,890", change: 21 },
    { rank: 4, product_name: "비닐봉투 (중) 1000매", sales_count: "5,670", change: -5 },
    { rank: 5, product_name: "주방세제 3L 6개입", sales_count: "4,230", change: 8 },
  ],
  category_distribution: [
    { category: "소모품", percentage: 42 },
    { category: "식자재", percentage: 28 },
    { category: "포장재", percentage: 15 },
    { category: "인테리어", percentage: 9 },
    { category: "기타", percentage: 6 },
  ],
};

export const dummyBestSellers: BestSellerItem[] = [
  { rank: 1, product_name: "일회용 종이컵 6.5oz 1000개입", price: "박스 당 27,500원", sales_count: "1,246건" },
  { rank: 2, product_name: "아메리카노 원두 1kg (브라질산)", price: "7,600원", sales_count: "987건" },
  { rank: 3, product_name: "커피 필터 (백산화) 500매입", price: "8,210원", sales_count: "876건" },
  { rank: 4, product_name: "냅킨 2겹 200매 30팩", price: "4,120원", sales_count: "654건" },
  { rank: 5, product_name: "테이크아웃 커피컵 뚜껑 (1000개)", price: "4,870원", sales_count: "543건" },
];

export const dummySubscriptions: SubscriptionItem[] = [
  {
    id: "sub-1",
    product: dummyProducts[0],
    cycle: "월 1회",
    quantity: 1,
    next_delivery: "2025년 4월 5일 (목)",
    active: true,
  },
  {
    id: "sub-2",
    product: dummyProducts[1],
    cycle: "월 1회",
    quantity: 1,
    next_delivery: "2025년 4월 12일 (목)",
    active: false,
  },
];

export const categories = [
  { label: "식자재", icon: "🍳" },
  { label: "소모품", icon: "🧴" },
  { label: "포장재", icon: "📦" },
  { label: "뷰티용품", icon: "💄" },
  { label: "인테리어", icon: "🪑" },
  { label: "기타", icon: "📋" },
];

export const businessTypes = [
  "카페/베이커리",
  "한식/분식",
  "치킨/피자",
  "편의점/소매",
  "미용/뷰티",
  "배달/외식전반",
];

export const dummyUser = {
  id: "user-1",
  email: "test@bizmart.com",
  business_number: "220-81-62517",
  business_type: "카페/베이커리",
  company_name: "하늘빛 카페",
  owner_name: "김민준",
  created_at: "2025-03-01",
};
